const header_detail = [
  "Customer Name",
  "Application Amount",
  "Product Name",
  "Branch Name",
  "CBC Fee",
  "Loan Term TypeCode",
  "First Interest PaymentDate",
  "Collateral LoanRatio",
  "Collateral LoanYn",
  "Loan Expiry Date",
  "Loan Application Kind Code",
  "Fire Insurance Expiry Date",
  "House Corporation TypeCode",
  "Application Branch Code",
  "CBC Reference No",
  "Overdue Grace PeriodDays",
  "Loan Fund Purpose Code",
  "Total Interest Amount Ratio",
  "Interest Exemption Period",
  "Application Status Code",
  "CreditRisk Rating Score",
  "Loan Fund Purpose Amount",
  "Un Use Fee",
  "Loan Authority Code",
  "Loan Period Monthly Count",
  "Loan Fund Purpose Amount3",
  "Month Repay Amount",
  "Loan Fund Purpose Amount 2",
  "Overdue YN",
  "Remark 4",
  "Loan Grace Period Months",
  "Credit Bureau Combodia Grade",
  "Fund Source Code",
  "Calculation Collateral Loan Ratio",
  "Application Date",
  "Remark 2",
  "Credit Bureau Combodia Score",
  "Loan Product Code",
  "Loan Counsel No",
  "Status CD",
  "Fire Insurance Amount",
  "Standard Code Value Desc",
  "Application Handler EmployeeNo",
  "Link Transaction YN",
  "Loan Fund Purpose Code 3",
  "Loan Hope Date",
  "Loan Fund Purpose Code 2",
  "Employee Name 1",
  "Frequency TypeCode",
  "Grid 01 Count",
  "Fire Insurance Target YN",
  "Principal Repay Method Code",
  "CBC K Score",
  "Handle Fee",
  "Fee TypeCode",
  "Loan Application TypeCode",
  "Apply Interest Rate",
  "Payment Cycle Monthly",
  "Credit Risk Rating Grade",
  "Loan Approval Application No",
  "Currency Code",
  "Customer No",
  "Check Collection Amount",
];
