const header_detail = [
  "Name",
  "Application No",
  "Product Name",
  "Principle",
  "Currency",
  "Term",
  "Interest Rate",
  "Admin Fee",
  "CBC Fee",
  "Maintenance Fee",
  "Disburse Date",
  "Maturity Date",
  "Interest Exception",
  "Branch",
  "First Repay Date",
];
