const list_detail = [
  "customerName",
  "applicationAmount",
  "loanApprovalApplicationNo",
  "productName",
  "applicationAmount",
  "currencyCode",
  "loanPeriodMonthlyCount",
  "handleFee",
  "cbcFee",
  "unUseFee",
  "loanHopeDate",
  "loanExpiryDate",
  "interestExemptionPeriod",
  "branchName",
  "firstInterestPaymentDate",
];
